
[build]
  command = "npm run netlify:build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  EXPO_PUBLIC_CONVEX_URL = "${EXPO_PUBLIC_CONVEX_URL}"
  EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY = "${EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY}"
  EXPO_PUBLIC_PAYMONGO_SECRET_KEY = "${EXPO_PUBLIC_PAYMONGO_SECRET_KEY}"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
