import { StyleSheet } from "react-native";
import { COLORS, SLATE, SHADOW } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: SLATE.slate_50,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: SLATE.slate_50,
  },
  header: {
    backgroundColor: COLORS.primary,
    paddingTop: 60,
    paddingBottom: 24,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 24,
    ...SHADOW.lg,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    marginRight: 16,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.textOnPrimary,
  },
  headerSubtitle: {
    fontSize: 16,
    color: COLORS.textOnPrimary,
    opacity: 0.8,
    marginTop: 4,
  },
  headerInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  weightGoalTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  weightGoalText: {
    fontSize: 12,
    color: COLORS.textOnPrimary,
    marginLeft: 4,
    fontWeight: "500",
  },
  listContainer: {
    padding: 16,
  },
  exerciseCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    ...SHADOW.md,
  },
  exerciseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  exerciseName: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    flex: 1,
  },
  exerciseTypeTag: {
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  exerciseTypeTagModal: {
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    marginBottom: 16,
  },
  exerciseTypeText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textTransform: "capitalize",
  },
  exerciseDetails: {
    flexDirection: "row",
    marginBottom: 16,
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  detailText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  startButton: {
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    marginRight: 12,
  },
  startButtonText: {
    color: COLORS.textOnPrimary,
    fontWeight: "600",
    marginLeft: 4,
  },
  viewButton: {
    backgroundColor: COLORS.secondary,
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  viewButtonText: {
    color: COLORS.textOnSecondary,
    fontWeight: "600",
    marginLeft: 4,
  },
  timerContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.primary,
    padding: 16,
    alignItems: "center",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    ...SHADOW.lg,
  },
  timerText: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.textOnPrimary,
    marginBottom: 12,
  },
  stopButton: {
    backgroundColor: COLORS.error,
    flexDirection: "row",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  stopButtonText: {
    color: COLORS.textOnPrimary,
    fontWeight: "600",
    marginLeft: 4,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.5)", // slate_900 with opacity
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    padding: 24,
    borderRadius: 16,
    width: "90%",
    maxHeight: "80%",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  modalDetailsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  modalDetailItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  modalDetailText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginLeft: 8,
  },
  instructionsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  modalInstructions: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginBottom: 16,
    lineHeight: 24,
  },
  videoContainer: {
    width: "100%",
    height: 250,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    backgroundColor: COLORS.surfaceAlt,
  },
  videoOverlay: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  videoPlayer: {
    width: "100%",
    height: "100%",
    backgroundColor: "#000",
  },
  playButtonOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  videoPlaceholder: {
    width: "100%",
    height: 160,
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  videoPlaceholderText: {
    color: COLORS.textTertiary,
    fontSize: 14,
    marginTop: 8,
  },
  videoPlayText: {
    color: COLORS.textOnPrimary,
    fontSize: 14,
    fontWeight: "600",
    marginTop: 8,
  },
  videoPreviewContainer: {
    width: "100%",
    height: 100,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    marginBottom: 12,
    overflow: "hidden",
  },
  videoPreviewOverlay: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  videoPreviewText: {
    color: COLORS.textOnPrimary,
    fontSize: 14,
    fontWeight: "600",
    marginTop: 8,
  },
  closeButton: {
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    width: "100%",
  },
  closeButtonText: {
    color: COLORS.textOnPrimary,
    fontWeight: "600",
    fontSize: 16,
  },
});
