import { StyleSheet } from "react-native";
import { COLORS, FONT, SPACING, RADIUS, SHADOW, SLATE } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: SLATE.slate_50,
  },
  loadingContainer: {
    padding: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: SPACING.sm,
    fontSize: FONT.size.md,
    color: COLORS.textSecondary,
  },
  header: {
    backgroundColor: SLATE.slate_800,
    paddingTop: 60,
    paddingBottom: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    marginBottom: SPACING.lg,
    shadowColor: SLATE.slate_900,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: SLATE.slate_700,
  },
  headerTitle: {
    fontSize: FONT.size.xxxl,
    fontWeight: FONT.weight.bold,
    color: COLORS.textOnPrimary,
    marginBottom: SPACING.xs,
  },
  headerSubtitle: {
    fontSize: FONT.size.md,
    color: COLORS.textOnPrimary,
    opacity: 0.9,
  },
  planSelectionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.md,
  },
  planButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.lg,
    backgroundColor: SLATE.slate_50,
    flex: 1,
    marginHorizontal: SPACING.xs,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    shadowColor: SLATE.slate_300,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  selectedPlanButton: {
    backgroundColor: SLATE.slate_800,
    borderColor: SLATE.slate_800,
  },
  planButtonText: {
    fontSize: FONT.size.sm,
    fontWeight: FONT.weight.semibold,
    color: SLATE.slate_700,
    marginLeft: SPACING.xs,
  },
  selectedPlanButtonText: {
    color: COLORS.textOnPrimary,
  },
  listContainer: {
    paddingHorizontal: SPACING.md,
    paddingBottom: 100,
  },
  dayContainer: {
    marginBottom: SPACING.md,
    backgroundColor: SLATE.slate_50,
    borderRadius: RADIUS.xl,
    overflow: "hidden",
    shadowColor: SLATE.slate_300,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
  },
  dayHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACING.md,
    backgroundColor: SLATE.slate_100,
    borderBottomWidth: 1,
    borderBottomColor: SLATE.slate_200,
  },
  dayHeaderContent: {
    flex: 1,
  },
  dayText: {
    fontSize: FONT.size.lg,
    fontWeight: FONT.weight.bold,
    color: COLORS.textPrimary,
  },
  dailyTotalsContainer: {
    marginTop: SPACING.xs,
  },
  dailyTotalsText: {
    fontSize: FONT.size.sm,
    color: COLORS.textSecondary,
  },
  mealsContainer: {
    padding: SPACING.md,
  },
  nutritionSummary: {
    marginTop: SPACING.md,
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
  },
  nutritionSummaryTitle: {
    fontSize: FONT.size.md,
    fontWeight: FONT.weight.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
  },
  nutritionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  nutritionItem: {
    alignItems: "center",
  },
  nutritionValue: {
    fontSize: FONT.size.lg,
    fontWeight: FONT.weight.bold,
    color: COLORS.primary,
  },
  nutritionLabel: {
    fontSize: FONT.size.xs,
    color: COLORS.textSecondary,
    marginTop: SPACING.xs,
  },
  addedMealsContainer: {
    marginTop: SPACING.sm,
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
  },
  addedMealsTitle: {
    fontWeight: FONT.weight.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  addedMealItem: {
    color: COLORS.textPrimary,
    marginLeft: SPACING.xs,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: `rgba(15, 23, 42, 0.7)`, // slate_900 with opacity
  },
  modalContent: {
    backgroundColor: SLATE.slate_50,
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    width: "92%",
    maxHeight: "80%",
    shadowColor: SLATE.slate_900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
  },
  modalTitle: {
    fontSize: FONT.size.xl,
    fontWeight: FONT.weight.bold,
    color: COLORS.primary,
    marginBottom: SPACING.md,
    textAlign: "center",
  },
  label: {
    fontSize: FONT.size.sm,
    fontWeight: FONT.weight.bold,
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  input: {
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    marginBottom: SPACING.md,
    fontSize: FONT.size.sm,
    color: SLATE.slate_700,
    backgroundColor: SLATE.slate_50,
  },
  mealTypeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  mealTypeButton: {
    flex: 1,
    padding: SPACING.sm,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: RADIUS.md,
    alignItems: "center",
    marginHorizontal: SPACING.xs,
    backgroundColor: SLATE.slate_50,
  },
  mealTypeButtonActive: {
    backgroundColor: SLATE.slate_800,
    borderColor: SLATE.slate_800,
  },
  mealTypeButtonText: {
    fontSize: FONT.size.sm,
    color: SLATE.slate_500,
  },
  mealTypeButtonTextActive: {
    color: COLORS.textOnPrimary,
  },
  addButton: {
    backgroundColor: COLORS.primary,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    marginTop: SPACING.md,
  },
  addButtonText: {
    color: COLORS.textOnPrimary,
    fontWeight: FONT.weight.bold,
    fontSize: FONT.size.md,
  },
  closeButton: {
    backgroundColor: COLORS.secondary,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    marginTop: SPACING.xs,
  },
  closeButtonText: {
    color: COLORS.textOnSecondary,
    fontWeight: FONT.weight.bold,
    fontSize: FONT.size.md,
  },
  addMealButton: {
    backgroundColor: COLORS.primary,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    marginTop: SPACING.xs,
  },
  addMealButtonText: {
    color: COLORS.textOnPrimary,
    fontWeight: FONT.weight.bold,
    fontSize: FONT.size.md,
  },
  recommendButton: {
    backgroundColor: COLORS.secondary,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    marginTop: SPACING.xs,
    marginBottom: SPACING.sm,
  },
  recommendButtonText: {
    color: COLORS.textOnSecondary,
    fontWeight: FONT.weight.bold,
    fontSize: FONT.size.md,
  },
  recommendationsList: {
    height: 300,
    flexGrow: 0,
  },
  recommendationItem: {
    flexDirection: "row",
    padding: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: SLATE.slate_200,
    alignItems: "center",
    backgroundColor: SLATE.slate_50,
    marginBottom: SPACING.xs,
    borderRadius: RADIUS.md,
  },
  recommendationItemSelected: {
    backgroundColor: `${COLORS.primary}10`,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
  },
  recommendationContent: {
    flex: 1,
    marginLeft: SPACING.sm,
  },
  recommendationName: {
    fontSize: FONT.size.md,
    fontWeight: FONT.weight.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  recommendationDescription: {
    fontSize: FONT.size.sm,
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  recommendationMacros: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  macroPill: {
    backgroundColor: COLORS.surfaceAlt,
    paddingVertical: SPACING.xs / 2,
    paddingHorizontal: SPACING.xs,
    borderRadius: RADIUS.sm,
    marginRight: SPACING.xs,
    marginBottom: SPACING.xs,
  },
  macroPillText: {
    fontSize: FONT.size.xs,
    color: COLORS.textSecondary,
  },
  categoryIndicator: {
    width: 12,
    height: 12,
    borderRadius: RADIUS.round,
    marginRight: SPACING.xs,
  },
  recommendationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  recommendationTitle: {
    fontSize: FONT.size.xl,
    fontWeight: FONT.weight.bold,
    color: COLORS.primary,
  },
  filterContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: SPACING.md,
  },
  filterPill: {
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    borderRadius: RADIUS.round,
    marginRight: SPACING.xs,
    marginBottom: SPACING.xs,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    backgroundColor: SLATE.slate_50,
  },
  filterPillSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  filterPillText: {
    fontSize: FONT.size.xs,
    color: COLORS.textSecondary,
  },
  filterPillTextSelected: {
    color: COLORS.textOnPrimary,
  },
  noRecommendations: {
    padding: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  noRecommendationsText: {
    fontSize: FONT.size.md,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  mealTypeButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  selectedMealTypeButton: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  selectedMealTypeButtonText: {
    color: COLORS.textOnPrimary,
  },
  disabledButton: {
    backgroundColor: COLORS.border,
    opacity: 0.7,
  },
  searchResultsContainer: {
    marginBottom: SPACING.md,
  },
  searchResults: {
    maxHeight: 200,
    backgroundColor: SLATE.slate_50,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.sm,
  },
  searchResultItem: {
    padding: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: SLATE.slate_200,
  },
});