import { StyleSheet } from "react-native";
import { COLORS, SPACING, RADIUS, SHADOW, SLATE } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    borderRadius: RADIUS.lg,
    overflow: "hidden",
    ...SHADOW.md,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
  },
  buttonContainer: {
    width: "100%",
    alignItems: "center",
  },
  permissionContainer: {
    padding: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  permissionTitle: {
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
    textAlign: "center",
    color: SLATE.slate_800,
  },
  permissionText: {
    textAlign: "center",
    marginBottom: SPACING.sm,
    color: SLATE.slate_600,
    lineHeight: 20,
  },
  permissionNote: {
    textAlign: "center",
    marginTop: SPACING.md,
    fontSize: 12,
    color: SLATE.slate_500,
    fontStyle: "italic",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: SLATE.slate_100,
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  title: {
    marginLeft: 8,
  },
  goalButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: SLATE.slate_100,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.md,
  },
  content: {
    padding: SPACING.md,
    alignItems: "center",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: SPACING.md,
    backgroundColor: SLATE.slate_50,
    borderRadius: RADIUS.lg,
    padding: SPACING.sm,
    ...SHADOW.sm,
  },
  statItem: {
    alignItems: "center",
    padding: SPACING.sm,
    minWidth: 80,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: SLATE.slate_800,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: SLATE.slate_500,
    fontWeight: "500",
  },
  goalMessage: {
    marginTop: SPACING.md,
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
    borderLeftWidth: 3,
    width: "100%",
  },
  goalMessageSuccess: {
    borderLeftColor: COLORS.success,
    backgroundColor: `${COLORS.success}10`,
  },
  goalMessagePending: {
    borderLeftColor: SLATE.slate_500,
    backgroundColor: `${SLATE.slate_500}10`,
  },
  unavailableContainer: {
    padding: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  unavailableText: {
    textAlign: "center",
    marginTop: SPACING.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    width: "80%",
    ...SHADOW.lg,
  },
  modalTitle: {
    marginBottom: SPACING.sm,
    textAlign: "center",
  },
  modalDescription: {
    fontSize: 14,
    color: SLATE.slate_600,
    textAlign: "center",
    marginBottom: SPACING.md,
  },
  input: {
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    fontSize: 16,
    marginBottom: SPACING.md,
    textAlign: "center",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  presetContainer: {
    marginBottom: SPACING.md,
  },
  presetLabel: {
    fontSize: 13,
    color: SLATE.slate_600,
    marginBottom: 6,
  },
  presetButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  presetButton: {
    backgroundColor: SLATE.slate_100,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
  },
  presetButtonText: {
    fontSize: 13,
    color: SLATE.slate_700,
    fontWeight: "500",
  },
  walkingStatusContainer: {
    width: "100%",
    marginTop: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  walkingStatusIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${COLORS.primary}10`,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.md,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
    flex: 1,
  },
  walkingIcon: {
    marginRight: 8,
  },
  walkingStatusText: {
    color: SLATE.slate_700,
    fontSize: 13,
    fontWeight: "500",
  },
  enableTrackingButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  enableTrackingText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  buttonIcon: {
    marginRight: 6,
  },
  resetButton: {
    backgroundColor: SLATE.slate_500,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  resetButtonText: {
    color: COLORS.white,
    fontWeight: "500",
    fontSize: 13,
  },
  motionStatusContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    backgroundColor: SLATE.slate_50,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
  },
  motionStatusIndicator: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusDotActive: {
    backgroundColor: COLORS.success,
  },
  statusDotInactive: {
    backgroundColor: SLATE.slate_400,
  },
  motionStatusText: {
    fontSize: 12,
  },
  permissionButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.md,
  },
  permissionButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "500",
  },
  devicePositionContainer: {
    width: "100%",
    marginTop: SPACING.sm,
    padding: SPACING.sm,
    backgroundColor: SLATE.slate_50,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: SLATE.slate_200,
  },
  devicePositionLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: SLATE.slate_600,
    marginBottom: 4,
  },
  devicePositionIndicator: {
    flexDirection: "row",
    alignItems: "center",
  },
  devicePositionText: {
    fontSize: 12,
    fontWeight: "500",
  },
});
