import { StyleSheet } from "react-native";
import { COLORS, SLATE, SHADOW, SPACING } from "@/constants/theme";
import { commonStyles } from "./commonStyles";

export const styles = StyleSheet.create({
  ...commonStyles,
  // Specific workout styles
  goalSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  goalButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    flex: 1,
    marginHorizontal: 4,
    justifyContent: "center",
  },
  activeGoalButton: {
    backgroundColor: COLORS.secondary,
  },
  goalButtonText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginLeft: 4,
    fontWeight: "500",
  },
  activeGoalButtonText: {
    color: COLORS.textOnPrimary,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: -30,
    marginBottom: 16,
  },
  statCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    width: "30%",
    ...SHADOW.md,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginTop: 8,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  sectionContainer: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    ...SHADOW.sm,
  },
  sectionTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  addButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 8,
  },
  addButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  exerciseItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: SPACING.sm,
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 8,
    marginBottom: SPACING.sm,
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  exerciseDetails: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  exerciseActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  timerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceLight,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: 6,
    gap: SPACING.xs,
  },
  deleteButton: {
    backgroundColor: COLORS.error,
    padding: 8,
    borderRadius: 8,
    marginLeft: 8,
  },
  editButton: {
    backgroundColor: COLORS.secondary,
    padding: 8,
    borderRadius: 8,
    marginLeft: 8,
  },
  modalDeleteButton: {
    backgroundColor: COLORS.error,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  deleteButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  swipeableActions: {
    flexDirection: "row",
    width: 100,
    height: "100%",
  },
  swipeDeleteButton: {
    backgroundColor: COLORS.error,
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: "100%",
  },
  swipeButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  completeButton: {
    backgroundColor: COLORS.secondary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  completedButton: {
    backgroundColor: COLORS.success,
  },
  completeButtonText: {
    color: COLORS.textOnSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  timerDisplay: {
    alignItems: "center",
    marginVertical: SPACING.lg,
  },
  timerText: {
    fontSize: 48,
    fontWeight: "bold",
    color: COLORS.primary,
    fontVariant: ["tabular-nums"],
  },
  timerControls: {
    flexDirection: "row",
    justifyContent: "center",
    gap: SPACING.md,
    marginBottom: SPACING.lg,
  },
  timerControlButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceLight,
    padding: SPACING.sm,
    borderRadius: 8,
    gap: SPACING.xs,
  },
  timerControlText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    marginTop: 8,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.xl,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: COLORS.textTertiary,
    textAlign: "center",
  },
  weekdayCard: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    width: 140,
    alignItems: "center",
  },
  todayCard: {
    backgroundColor: COLORS.primary,
  },
  weekdayText: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  todayText: {
    color: COLORS.textOnPrimary,
  },
  exerciseCount: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  weekdayActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  weekdayActionText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  weightGoalTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  weightGoalText: {
    fontSize: 12,
    color: COLORS.textOnPrimary,
    marginLeft: 4,
    fontWeight: "500",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.7)", // Darker background for better contrast
    paddingHorizontal: SPACING.md,
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: SPACING.xl,
    width: "90%",
    maxHeight: "90%",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: SPACING.lg,
    textAlign: "center",
  },
  input: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontSize: 16,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
  },
  matchingText: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: "600",
    marginTop: 4,
    marginBottom: 8,
    textAlign: "center",
    backgroundColor: SLATE.slate_100,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  typeSelector: {
    marginBottom: 16,
  },
  typeLabel: {
    fontSize: 16,
    color: COLORS.textPrimary,
    marginBottom: 8,
    fontWeight: "600",
  },
  categoryContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  categoryButton: {
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
    width: "48%",
    alignItems: "center",
  },
  selectedCategoryButton: {
    backgroundColor: COLORS.primary,
  },
  categoryButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  selectedCategoryButtonText: {
    color: COLORS.textOnPrimary,
  },
  typeButton: {
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  selectedTypeButton: {
    backgroundColor: COLORS.primary,
  },
  typeButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  selectedTypeButtonText: {
    color: COLORS.textOnPrimary,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  cancelButton: {
    backgroundColor: COLORS.surfaceAlt,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
    marginRight: 8,
  },
  cancelButtonText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
    marginLeft: 8,
  },
  saveButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  closeButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    borderRadius: 8,
    alignItems: "center",
  },
  closeButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  historyItem: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 8,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
  },
  historyDate: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  historyDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SPACING.sm,
  },
  historyDetail: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  historyValue: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  caloriesContainer: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  caloriesLabel: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontWeight: "500",
  },
  caloriesValue: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: "bold",
  },
  caloriesHint: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 16,
    fontStyle: "italic",
  },
  seedButton: {
    backgroundColor: COLORS.secondary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 16,
    alignSelf: "center",
  },
  seedButtonText: {
    color: COLORS.textOnSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  searchResultsContainer: {
    marginBottom: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: 8,
    padding: 8,
    backgroundColor: SLATE.slate_100,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    maxHeight: 250,
    overflow: "hidden", // Changed to hidden to prevent overflow issues
    zIndex: 1, // Reduced to prevent layering issues
  },
  searchResults: {
    maxHeight: 200,
    backgroundColor: SLATE.slate_50,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: 8,
    marginBottom: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 1,
    zIndex: 1,
  },
  searchResultItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: SLATE.slate_200,
    backgroundColor: COLORS.surface,
    marginHorizontal: 2,
    marginVertical: 2,
    borderRadius: 4,
  },
  searchResultItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  searchResultItemDetails: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
});
