import { StyleSheet } from "react-native";
import { COLORS, SLATE, SHADOW } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: SLATE.slate_50,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: SLATE.slate_50,
  },
  header: {
    backgroundColor: COLORS.primary,
    paddingTop: 60,
    paddingBottom: 24,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    ...SHADOW.lg,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.textOnPrimary,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 16,
    color: COLORS.textOnPrimary,
    opacity: 0.8,
    marginBottom: 16,
  },
  goalSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  goalButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    flex: 1,
    marginHorizontal: 4,
    justifyContent: "center",
  },
  activeGoalButton: {
    backgroundColor: COLORS.secondary,
  },
  goalButtonText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginLeft: 4,
    fontWeight: "500",
  },
  activeGoalButtonText: {
    color: COLORS.textOnPrimary,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: -30,
    marginBottom: 16,
  },
  statCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    width: "30%",
    ...SHADOW.md,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginTop: 8,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  sectionContainer: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    ...SHADOW.sm,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  addButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  addButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  exerciseItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  exerciseDetails: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  exerciseActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  timerButton: {
    backgroundColor: COLORS.surfaceAlt,
    padding: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  deleteButton: {
    backgroundColor: COLORS.error,
    padding: 8,
    borderRadius: 8,
    marginLeft: 8,
  },
  editButton: {
    backgroundColor: COLORS.secondary,
    padding: 8,
    borderRadius: 8,
    marginLeft: 8,
  },
  modalDeleteButton: {
    backgroundColor: COLORS.error,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  deleteButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  swipeableActions: {
    flexDirection: "row",
    width: 100,
    height: "100%",
  },
  swipeDeleteButton: {
    backgroundColor: COLORS.error,
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: "100%",
  },
  swipeButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  completeButton: {
    backgroundColor: COLORS.secondary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  completedButton: {
    backgroundColor: COLORS.success,
  },
  completeButtonText: {
    color: COLORS.textOnSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  timerDisplay: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 24,
  },
  timerText: {
    fontSize: 48,
    fontWeight: "bold",
    color: COLORS.primary,
    fontVariant: ["tabular-nums"],
  },
  timerControls: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 24,
  },
  timerControlButton: {
    alignItems: "center",
    padding: 12,
  },
  timerControlText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    marginTop: 8,
  },
  emptyContainer: {
    alignItems: "center",
    paddingVertical: 24,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: COLORS.textTertiary,
    textAlign: "center",
  },
  weekdayCard: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    width: 140,
    alignItems: "center",
  },
  todayCard: {
    backgroundColor: COLORS.primary,
  },
  weekdayText: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  todayText: {
    color: COLORS.textOnPrimary,
  },
  exerciseCount: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  weekdayActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  weekdayActionText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  weightGoalTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  weightGoalText: {
    fontSize: 12,
    color: COLORS.textOnPrimary,
    marginLeft: 4,
    fontWeight: "500",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.5)", // slate_900 with opacity
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxHeight: "80%",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 16,
    textAlign: "center",
  },
  input: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontSize: 16,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
  },
  matchingText: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: "600",
    marginTop: 4,
    marginBottom: 8,
    textAlign: "center",
    backgroundColor: SLATE.slate_100,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  typeSelector: {
    marginBottom: 16,
  },
  typeLabel: {
    fontSize: 16,
    color: COLORS.textPrimary,
    marginBottom: 8,
    fontWeight: "600",
  },
  categoryContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  categoryButton: {
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
    width: "48%",
    alignItems: "center",
  },
  selectedCategoryButton: {
    backgroundColor: COLORS.primary,
  },
  categoryButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  selectedCategoryButtonText: {
    color: COLORS.textOnPrimary,
  },
  typeButton: {
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  selectedTypeButton: {
    backgroundColor: COLORS.primary,
  },
  typeButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  selectedTypeButtonText: {
    color: COLORS.textOnPrimary,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  cancelButton: {
    backgroundColor: COLORS.surfaceAlt,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
    marginRight: 8,
  },
  cancelButtonText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    flex: 1,
    marginLeft: 8,
  },
  saveButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  closeButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 16,
  },
  closeButtonText: {
    color: COLORS.textOnPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  historyItem: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingVertical: 12,
  },
  historyDate: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  historyDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  historyDetail: {
    flexDirection: "row",
    alignItems: "center",
  },
  historyValue: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  caloriesContainer: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  caloriesLabel: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontWeight: "500",
  },
  caloriesValue: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: "bold",
  },
  caloriesHint: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 16,
    fontStyle: "italic",
  },
  seedButton: {
    backgroundColor: COLORS.secondary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 16,
    alignSelf: "center",
  },
  seedButtonText: {
    color: COLORS.textOnSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  searchResultsContainer: {
    marginBottom: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: 8,
    padding: 8,
    backgroundColor: SLATE.slate_100,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  searchResults: {
    maxHeight: 150, // Reduced height to prevent overflow
    backgroundColor: SLATE.slate_50,
    borderWidth: 1,
    borderColor: SLATE.slate_300,
    borderRadius: 8,
    marginBottom: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  searchResultItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: SLATE.slate_200,
    backgroundColor: COLORS.surface,
    marginHorizontal: 2,
    marginVertical: 2,
    borderRadius: 6,
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  searchResultItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  searchResultItemDetails: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
});
